// Republic Quiz Data - All country data and bonus questions

var quizData = [
    { country: "The Islamic Republic of Afghanistan", correct: "Islamic", options: ["Islamic", "Democratic", "Federal", "People's"], capital: "Kabul", capitalOptions: ["Kabul", "Islamabad", "Tehran", "Baghdad"], language: "Pashto", languageOptions: ["Pashto", "Dari", "Urdu", "Persian"], flag: "af", flagOptions: ["af", "pk", "ir", "iq"] },
    { country: "The People's Democratic Republic of Algeria", correct: "People's Democratic", options: ["People's Democratic", "Democratic", "Arab", "Federal"], capital: "Algiers", capitalOptions: ["Algiers", "Tunis", "Rabat", "Cairo"], language: "Arabic", languageOptions: ["Arabic", "French", "Berber", "Spanish"], flag: "dz", flagOptions: ["dz", "tn", "ma", "eg"] },
    { country: "The People's Republic of Bangladesh", correct: "People's", options: ["People's", "Democratic", "Islamic", "Federal"], capital: "Dhaka", capitalOptions: ["Dhaka", "Islamabad", "New Delhi", "Kathmandu"], language: "Bengali", languageOptions: ["Bengali", "Hindi", "Urdu", "English"], flag: "bd", flagOptions: ["bd", "pk", "in", "np"] },
    { country: "The Federative Republic of Brazil", correct: "Federative", options: ["Federative", "Federal", "Democratic", "United"], capital: "Brasília", capitalOptions: ["Brasília", "Rio de Janeiro", "São Paulo", "Buenos Aires"], language: "Portuguese", languageOptions: ["Portuguese", "Spanish", "English", "French"], flag: "br", flagOptions: ["br", "ar", "co", "ve"] },
    { country: "The People's Republic of China", correct: "People's", options: ["People's", "Communist", "Democratic", "Socialist"], capital: "Beijing", capitalOptions: ["Beijing", "Shanghai", "Tokyo", "Seoul"], language: "Mandarin Chinese", languageOptions: ["Mandarin Chinese", "Cantonese", "Japanese", "Korean"], flag: "cn", flagOptions: ["cn", "jp", "kr", "tw"] },
    { country: "The Democratic Republic of the Congo", correct: "Democratic", options: ["Democratic", "Federal", "People's", "Central"], capital: "Kinshasa", capitalOptions: ["Kinshasa", "Brazzaville", "Luanda", "Libreville"], language: "Lingala", languageOptions: ["Lingala", "French", "Swahili", "Kikongo"], flag: "cd", flagOptions: ["cd", "cg", "ao", "ga"] },
    { country: "The Arab Republic of Egypt", correct: "Arab", options: ["Arab", "Islamic", "Democratic", "United"], capital: "Cairo", capitalOptions: ["Cairo", "Alexandria", "Khartoum", "Tripoli"], language: "Arabic", languageOptions: ["Arabic", "English", "French", "Coptic"], flag: "eg", flagOptions: ["eg", "sd", "ly", "sy"] },
    { country: "The Federal Democratic Republic of Ethiopia", correct: "Federal Democratic", options: ["Federal Democratic", "Democratic", "Federal", "People's"], capital: "Addis Ababa", capitalOptions: ["Addis Ababa", "Nairobi", "Khartoum", "Asmara"], language: "Amharic", languageOptions: ["Amharic", "Oromo", "English", "Arabic"], flag: "et", flagOptions: ["et", "ke", "sd", "er"] },
    { country: "The Federal Republic of Germany", correct: "Federal", options: ["Federal", "Democratic", "United", "Social"], capital: "Berlin", capitalOptions: ["Berlin", "Munich", "Frankfurt", "Vienna"], language: "German", languageOptions: ["German", "English", "French", "Dutch"], flag: "de", flagOptions: ["de", "at", "nl", "be"] },
    { country: "The Co-operative Republic of Guyana", correct: "Co-operative", options: ["Co-operative", "Democratic", "Federal", "United"], capital: "Georgetown", capitalOptions: ["Georgetown", "Paramaribo", "Cayenne", "Port of Spain"], language: "English", languageOptions: ["English", "Dutch", "Spanish", "Portuguese"], flag: "gy", flagOptions: ["gy", "sr", "gf", "tt"] },
    { country: "The Islamic Republic of Iran", correct: "Islamic", options: ["Islamic", "Persian", "Democratic", "Federal"], capital: "Tehran", capitalOptions: ["Tehran", "Isfahan", "Baghdad", "Kabul"], language: "Persian", languageOptions: ["Persian", "Arabic", "Turkish", "Kurdish"], flag: "ir", flagOptions: ["ir", "iq", "tr", "af"] },
    { country: "The Democratic People's Republic of Korea (North)", correct: "Democratic People's", options: ["Democratic People's", "People's", "Socialist", "Communist"], capital: "Pyongyang", capitalOptions: ["Pyongyang", "Seoul", "Beijing", "Tokyo"], language: "Korean", languageOptions: ["Korean", "Chinese", "Japanese", "Russian"], flag: "kp", flagOptions: ["kp", "kr", "cn", "jp"] },
    { country: "The Islamic Republic of Mauritania", correct: "Islamic", options: ["Islamic", "Arab", "Democratic", "Federal"], capital: "Nouakchott", capitalOptions: ["Nouakchott", "Dakar", "Bamako", "Rabat"], language: "Arabic", languageOptions: ["Arabic", "French", "Wolof", "Berber"], flag: "mr", flagOptions: ["mr", "sn", "ml", "ma"] },
    { country: "The Federal Republic of Nigeria", correct: "Federal", options: ["Federal", "Democratic", "United", "People's"], capital: "Abuja", capitalOptions: ["Abuja", "Lagos", "Accra", "Yaoundé"], language: "Hausa", languageOptions: ["Hausa", "Yoruba", "Igbo", "English"], flag: "ng", flagOptions: ["ng", "gh", "cm", "bj"] },
    { country: "The Islamic Republic of Pakistan", correct: "Islamic", options: ["Islamic", "Democratic", "Federal", "People's"], capital: "Islamabad", capitalOptions: ["Islamabad", "Karachi", "Lahore", "New Delhi"], language: "Punjabi", languageOptions: ["Punjabi", "Urdu", "Sindhi", "English"], flag: "pk", flagOptions: ["pk", "in", "bd", "af"] },
    { country: "The Democratic Republic of Sao Tome and Principe", correct: "Democratic", options: ["Democratic", "Federal", "Island", "Atlantic"], capital: "São Tomé", capitalOptions: ["São Tomé", "Malabo", "Libreville", "Luanda"], language: "Portuguese", languageOptions: ["Portuguese", "Spanish", "French", "English"], flag: "st", flagOptions: ["st", "gq", "ga", "ao"] },
    { country: "The Federal Republic of Somalia", correct: "Federal", options: ["Federal", "Democratic", "Islamic", "Horn"], capital: "Mogadishu", capitalOptions: ["Mogadishu", "Addis Ababa", "Nairobi", "Djibouti"], language: "Somali", languageOptions: ["Somali", "Arabic", "English", "Amharic"], flag: "so", flagOptions: ["so", "et", "ke", "dj"] },
    { country: "The Democratic Socialist Republic of Sri Lanka", correct: "Democratic Socialist", options: ["Democratic Socialist", "Socialist", "Democratic", "Island"], capital: "Colombo", capitalOptions: ["Colombo", "New Delhi", "Dhaka", "Malé"], language: "Sinhala", languageOptions: ["Sinhala", "Tamil", "English", "Hindi"], flag: "lk", flagOptions: ["lk", "in", "bd", "mv"] },
    { country: "The United Republic of Tanzania", correct: "United", options: ["United", "Federal", "Democratic", "East African"], capital: "Dodoma", capitalOptions: ["Dodoma", "Dar es Salaam", "Nairobi", "Kampala"], language: "Swahili", languageOptions: ["Swahili", "English", "Arabic", "French"], flag: "tz", flagOptions: ["tz", "ke", "ug", "rw"] },
    { country: "The Democratic Republic of Timor-Leste", correct: "Democratic", options: ["Democratic", "Federal", "Independent", "East"], capital: "Dili", capitalOptions: ["Dili", "Jakarta", "Kuala Lumpur", "Manila"], language: "Tetum", languageOptions: ["Tetum", "Portuguese", "Indonesian", "English"], flag: "tl", flagOptions: ["tl", "id", "my", "ph"] },
    { country: "The Oriental Republic of Uruguay", correct: "Oriental", options: ["Oriental", "Eastern", "Democratic", "Federal"], capital: "Montevideo", capitalOptions: ["Montevideo", "Buenos Aires", "Asunción", "Santiago"], language: "Spanish", languageOptions: ["Spanish", "Portuguese", "English", "Italian"], flag: "uy", flagOptions: ["uy", "ar", "py", "cl"] },
    { country: "The Bolivarian Republic of Venezuela", correct: "Bolivarian", options: ["Bolivarian", "Democratic", "Socialist", "South American"], capital: "Caracas", capitalOptions: ["Caracas", "Bogotá", "Georgetown", "Brasília"], language: "Spanish", languageOptions: ["Spanish", "Portuguese", "English", "Indigenous"], flag: "ve", flagOptions: ["ve", "co", "gy", "br"] },
    { country: "The Socialist Republic of Vietnam", correct: "Socialist", options: ["Socialist", "Democratic", "People's", "Communist"], capital: "Hanoi", capitalOptions: ["Hanoi", "Ho Chi Minh City", "Bangkok", "Phnom Penh"], language: "Vietnamese", languageOptions: ["Vietnamese", "Chinese", "French", "English"], flag: "vn", flagOptions: ["vn", "th", "kh", "la"] }
];

// Super Bonus Questions
var superBonusQuestions = [
    { question: "Which republic has the largest land area?", options: ["Brazil", "China", "Algeria", "Democratic Republic of Congo"], correct: "Brazil", explanation: "Brazil has 8.5 million km², making it the largest republic by area." },
    { question: "Which republic has the largest population?", options: ["China", "Nigeria", "Pakistan", "Bangladesh"], correct: "China", explanation: "China has over 1.4 billion people, the world's largest population." },
    { question: "Which republic has the smallest population?", options: ["Sao Tome and Principe", "Guyana", "Timor-Leste", "Uruguay"], correct: "Sao Tome and Principe", explanation: "Sao Tome and Principe has only about 219,000 people." },
    { question: "Which republic is most densely populated (people per km²)?", options: ["Bangladesh", "South Korea", "Sri Lanka", "Germany"], correct: "Bangladesh", explanation: "Bangladesh has over 1,100 people per km², one of the highest in the world." },
    { question: "Which republic was the first to adopt the 'Islamic Republic' designation?", options: ["Pakistan", "Iran", "Mauritania", "Afghanistan"], correct: "Pakistan", explanation: "Pakistan first adopted 'Islamic Republic' in its 1956 constitution." },
    { question: "Which republic spans the most time zones?", options: ["China", "Brazil", "Germany", "Algeria"], correct: "China", explanation: "China spans 5 time zones but officially uses only Beijing Time." },
    { question: "Which republic is the only one with 'Co-operative' in its official name?", options: ["Guyana", "Uruguay", "Tanzania", "Somalia"], correct: "Guyana", explanation: "Guyana is officially called 'The Co-operative Republic of Guyana', making it unique among world republics." }
];
